### ISSUE TITLE
UnboundLocalError: local variable 'key' referenced before assignment

### ISSUE THREAD

**Issue by BonnieToGamer** [Blatzar/schoolsoft-api-app#1]
Traceback (most recent call last):
  File "d:/softschool.py", line 8, in <module>
    token = schoolsoft_api.get_updated_token(app_key_json=app_key)['token']
  File "d:\schoolsoft_api.py", line 150, in get_updated_token
    token_json = get_token(app_key_json, app_key_path, write_file_path)
  File "d:\schoolsoft_api.py", line 58, in get_token
    "appkey": key,
UnboundLocalError: local variable 'key' referenced before assignment

**Comment by Blatzar** [comment]
Seems to happen when app_key_json is undefined e.g
![image](https://user-images.githubusercontent.com/46196380/90321569-4c11d600-df4b-11ea-8da7-09c9335ac464.png)
I'll add a warning when no app_key is provided

**Comment by Blatzar** [comment]
[Updated the script to include a warning](https://github.com/Blatzar/schoolsoft-api-app/commit/d84fc1e8b17e452564e3390432c9efab9c526c09)

**Comment by BonnieToGamer** [comment]
just a quick question how do i use this program? i can't figure it out from what you've written (i got the error when using your "usage" code)
edit: got new error `RuntimeError: No valid value for app_key. An app key is needed to generate the token`

**Comment by Blatzar** [comment]
Some variables in the usage code is left blank for privacy, I wouldn't want to give out my name and password. Replace those with your own, and if you don't trust that feel free to read the code. 

Name: schoolsoft username
Password: the password you use for schoolsoft. 
School, found in the url like this:
"https://sms13.schoolsoft.se/   _school_   /jsp/student/right_student_startpage.jsp"

The functions in here isn't very comple, they're made to be built on, they give the full api output, nothing very readable on its own, but easily sorted by another program.

**Comment by Blatzar** [comment]
Note that there might be an issue still with the code which may make it fail on other schools so let me know if it doesn't work for you.

**Comment by BonnieToGamer** [comment]
[like this?](https://imgur.com/a/KdNwMUY)

**Comment by BonnieToGamer** [comment]
i think i know the issue
edit: i was wrong
edit2: what i thought was the issue is that my schoolsoft says "https://sms.schoolsoft.se/" instead of "https://sms13.schoolsoft.se/"

**Comment by Blatzar** [comment]
Print app_key (dont post it) to see if it's valid. It should print something along the lines of this (values edited)
![image](https://user-images.githubusercontent.com/46196380/90322680-589c2b80-df57-11ea-807a-f7d4c3c96a65.png)

Example code snipped for the current week schedule I've used in my site.
```
import datetime
import schoolsoft_api
import re

def week_fixer(weeks):
    if not weeks:
        return []

    """
    Converts '3-8, 10-11, 13, 15-20, 22-23'
    to [3, 4, 5, 6, 7, 8, 10, 11, 13, 15, 16, 17, 18, 19, 20, 22, 23]
    """
    fixed_weeks = []
    weeks = weeks.split(',')

    for i in weeks:
        split = i.split('-')
        for j in range(int(split[0]),int(split[-1])+1):
            fixed_weeks.append(j)
    return fixed_weeks


def time_fixer(time):
    """
    converts: '1970-01-01 08:20:00.0'
    to: 08:20
    """
    time_regex = r'[0-2][0-9]:[0-6][0-9]'
    fixed_time = re.search(time_regex, time).group()
    return fixed_time

name = 'name' #FIX THESE
password = 'password'
school = 'school'

app_key = schoolsoft_api.get_app_key(name, password, write_file_path=None)
token = schoolsoft_api.get_updated_token(app_key_json=app_key, write_file_path=None)['token']
schedule = schoolsoft_api.get_lessons(token, school, write_file_path=None)

today = datetime.date.today()
current_year, current_week, current_day_of_week = today.isocalendar()

for day_id in [0,1,2,3,4]:
    for i in schedule:
        if i['dayId'] == day_id:
            schedule_weeks = week_fixer(i['weeksString'])
            if current_week in schedule_weeks:
                time_start = time_fixer(i['startTime'])
                time_end = time_fixer(i['endTime'])
                room_name = i['roomName']
                subject_name = i['subjectName']
                print(time_start,time_end,room_name, subject_name)
    print('\n\n')
```

**Comment by Blatzar** [comment]
I suspect your password/username is wrong since no app_key gets returned in that case, will add error. 
Note, you need to enable app access in the schoolsoft website. I'll add these in the instructions, forgot.
![image](https://user-images.githubusercontent.com/46196380/90322708-ba5c9580-df57-11ea-9e58-83d0fa7bca40.png)

**Comment by BonnieToGamer** [comment]
already had that active. Got a new the error, number 6
edit: grammar

**Comment by Blatzar** [comment]
> already had that active. Got a new the error, number 6

mind elaborating?
posting logs would help, I suspect it's the orgId bug

**Comment by BonnieToGamer** [comment]
`{'errorcodes': ['6'], 'errors': ['Användarnamnet eller lösenordet är felaktigt. <br />1. Har du skrivit rätt adress till inloggningssidan (finns din skolas logga på inloggningsidan)?<br />2. Har du valt rätt användartyp?<br />3. Har du skrivit rätt användarnamn?<br /><br />Om ovanstående stämmer - skapa ett nytt engångslösenord via länken &quot;Behöver du hjälp med inloggningen?&quot;.']}`

**Comment by BonnieToGamer** [comment]
i think the error comes because it automatically assumes I'm a parent/guardian

**Comment by Blatzar** [comment]
> i think the error comes because it automatically assumes I'm a parent/guardian

Nah I'm a student myself and use that login for testing. Does the same login credentials work in the official schoolsoft app?

**Comment by BonnieToGamer** [comment]
> Does the same login credentials work in the official schoolsoft app?

yes it does

**Comment by Blatzar** [comment]
Oh I found the culprit, the school is hardcoded into the app key function, I'll fix immediately.

**Comment by BonnieToGamer** [comment]
yeah i thought it looked weird

**Comment by Blatzar** [comment]
Try now with school as the first parameter in get_updated_token and 3rd parameter in get_app_key

**Comment by BonnieToGamer** [comment]
still get the same error
edit: in the get_app_key

**Comment by Blatzar** [comment]
Assuming you did a git reinstall instead of using the pip package and still get an error.
Try manually editing the [user and logintypes](https://github.com/Blatzar/schoolsoft-api-app/blob/master/schoolsoft_api/schoolsoft_api.py#L34-L35) until it works I suppose. Hard to debug since I don't have acces to more than one account.

**Comment by BonnieToGamer** [comment]
nope i used the pip install

**Comment by Blatzar** [comment]
I didn't update the pip package, hence why the error remains, will push soon™ use the git install in the meantime with `pip install git+https://github.com/Blatzar/schoolsoft-api-app`

**Comment by BonnieToGamer** [comment]
i don't know what i did but i managed to get it to work, kinda. 
if i do `print(schoolsoft_api.get_lessons(token, school))` i get the following error:
`Traceback (most recent call last):
  File "d:/Programmering/softschool/softschool.py", line 11, in <module>
    print(schoolsoft_api.get_lessons(token, school))
  File "d:\Programmering\softschool\schoolsoft_api.py", line 89, in get_lessons
    check_response(lesson_response)
  File "d:\Programmering\softschool\schoolsoft_api.py", line 23, in check_response
    raise ValueError("Unknown error with request")
ValueError: Unknown error with request
PS D:\Programmering\softschool> 
`

**Comment by Blatzar** [comment]
Update from git and try using the org_id parameter from your app_key
![image](https://user-images.githubusercontent.com/46196380/90323400-fb0cdc80-df60-11ea-84c8-b1c004084a1c.png)

For example `print(schoolsoft_api.get_lessons(token, school, 28))`
for this app_key, yours is different

**Comment by BonnieToGamer** [comment]
thanks man, works perfectly
