### ISSUE TITLE
get_app_key

### ISSUE THREAD

**Issue by Simple-MAX** [Blatzar/schoolsoft-api-app#2]
get_app_key function is not working

**Comment by Blatzar** [comment]
Are you sure you used the correct password, name, school and enabled mobile login on schoolsoft?

**Comment by Simple-MAX** [comment]
yes, I used my daily login info plus the school name.
what do you mean with enabled mobile login on schoolsoft?

**Comment by Blatzar** [comment]
In profile setting enable this, it uses the phone api.
![image](https://user-images.githubusercontent.com/46196380/91670164-42779900-eb1b-11ea-912b-aa4f4b903bcc.png)

**Comment by Simple-MAX** [comment]
yes

**Comment by Blatzar** [comment]
Will investigate tomorrow, the api may have been updated.

**Comment by Simple-MAX** [comment]
![pycharm64_jbRbcG51do](https://user-images.githubusercontent.com/19856805/91670291-52dc4380-eb1c-11ea-8033-883e0b3a6bdb.png)

**Comment by Simple-MAX** [comment]
I developed a web scraper in node js that gets the different information on the page but it's not really a good solution, so I'm looking for an alternative solution

**Comment by Blatzar** [comment]
That error means either the name/password is incorrect or that mobile access is disabled, however the school name a valid value.

Can you login to the schoolsoft app using the same credentials?
Worth checking out: https://sms.schoolsoft.se/rest/app/schoollist/prod 
Some schools seems to have restricted login methods, with "4" being the app (API) login method it seems.

**Comment by Simple-MAX** [comment]
thx it works now, I just had to change my password
